# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    steps:
    - script: | 
        echo Hello, world !! 
        echo Replace me with your build steps
      displayName: 'Build Script'
    - powershell: Write-Host "Run unit tests for your application."        
      displayName: 'Unit Testing'
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: drop
        targetPath: '$(Build.SourcesDirectory)'
- stage: Deploy
  displayName: Deploy stage
  jobs:
  - deployment: deploy
    displayName: Deploy job
    environment: 'myFirstEnvironment'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@1
            inputs:
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)/drop'
          - script: dir $(System.ArtifactsDirectory)/drop
          - powershell: Write-Host "run your deployment steps"

